server:
  error:
    whitelabel:
      enabled: false
  port: 4070
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 1q2w3e4r!
#    key-store-type: PKCS12
#    enabled: true
#    key-alias: bobtime-ssl

spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://144.24.74.58:3306/BT
      username: jhjh
      password: Wjd999888!
      minimum-idle: 2
      maximum-pool-size: 3
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.bobtime.common.strategy.CamelToSnakeUpperStrategy
    show-sql: true
    generate-ddl: false
    open-in-view: false












